name: flutton
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^1.0.13
  rxdart: ^0.20.0
  kiwi: ^0.1.0
  shimmer: ^0.0.6
  fluro: "^1.4.0"



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
